version: '3'

services:
  app:
    tty: true
    stdin_open: true
    entrypoint: [bin/start]
    image: cambioscience/greenlight:release-v2
    container_name: greenlight-v2
    env_file: .env
    restart: unless-stopped
    ports:
      - 127.0.0.1:5000:80
    volumes:
      - .:/usr/src/app
      - ./log:/usr/src/app/log
      - ./db/development:/usr/src/app/db/development

# When using external logging
#    logging:
#      driver: $LOG_DRIVER
#      options:
#        syslog-address: $LOG_ADDRESS
#        tag: $LOG_TAG


    # links:
    #   - db

  # db:
  #   image: postgres:9.5
  #   container_name: greenlight-db
  #   restart: on-failure
  #   ports:
  #     - 127.0.0.1:5432:5432
  #   volumes:
  #     - ./db/production:/var/lib/postgresql/data
  #   environment:
  #     - PGHOST=postgres
  #     - PGDATABASE=postgres
  #     - PGUSER=postgres
  #     - PGPASSWORD=password
